adimichele/hubspot-ruby

lib/hubspot-ruby.rb

Was getting the following error.  Followed advice from similar issue (https://github.com/huydx/facy/issues/17) to fix.
```
irb(main):001:0> require 'hubspot-ruby'
NameError: uninitialized constant ActiveSupport::Autoload
from /usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/number_helper.rb:3:in `<module:NumberHelper>'
from /usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/number_helper.rb:2:in `<module:ActiveSupport>'
from /usr/local/bundle/gems/activesupport-4.2.2/lib/active_support/number_helper.rb:1:in `<top (required)>'
...
```

Require active_support before active_support/core_ext

---

lib/hubspot/topic.rb
spec/fixtures/vcr_cassettes/topic_list.yml
spec/fixtures/vcr_cassettes/topics_list.yml

Hubspot depreciated v2 of Blog Topics API today 7/21
Fixes this issue
https://github.com/adimichele/hubspot-ruby/issues/21

changed Hubspot::Topic to use v3 api

---

lib/hubspot/connection.rb

#19
Documentation can be found here: http://developers.hubspot.com/docs/methods/forms/submit_form

Form Body should not be Encoded with JSON

---

lib/hubspot/connection.rb

If the `hapikey` param is included in the query string, then it will be visible in HubSpot.
Here's what HubSpot's Support Team said about this:
> [Our engineering team] indicated that this issue is you are passing a API submission through as a form param instead of a query param, when you are posting form submissions you do not need to include your hapikey.

`hapikey` param is not required for Forms API

---

lib/hubspot-ruby.rb
lib/hubspot/engagement.rb
spec/fixtures/vcr_cassettes/contact_create_or_update.yml
spec/fixtures/vcr_cassettes/contact_create_or_update_with_params.yml
spec/fixtures/vcr_cassettes/engagement_create.yml
spec/fixtures/vcr_cassettes/engagement_destroy.yml
spec/fixtures/vcr_cassettes/engagement_example.yml
spec/fixtures/vcr_cassettes/engagement_find.yml
spec/lib/hubspot/engagement_spec.rb

Added support for [engagements](http://developers.hubspot.com/docs/methods/engagements/create_engagement) and tried to match style/coverage standards. Currently only particularly useful with the `Hubspot:EngagementNote` subclass, but built in such a way to allow for future expansion.

Add support for Engagements and Engagement Notes

---

lib/hubspot/connection.rb
spec/lib/hubspot/connection_spec.rb

When query parameters contain special characters, call to server fails with the following error:
```
URI::InvalidURIError: bad URI(is not URI?):
```
To fix this, we need to properly encode and escape special characters for outgoing query parameters and paths.

URI encode query parameters

---

lib/hubspot/properties.rb
spec/lib/hubspot/company_properties_spec.rb
spec/lib/hubspot/contact_properties_spec.rb
spec/lib/hubspot/deal_properties_spec.rb

Properties.add_default_parameters was overwriting any passed in `property` key in the `opts` hash with the value `'email'`. This changes that so that `property: 'email'` will be set only if no `property` key already exists in the `opts` hash.
This should fix #61.

Fix overwriting passed in property options

---

lib/hubspot/contact.rb
lib/hubspot/contact_list.rb
spec/lib/hubspot/contact_list_spec.rb
spec/lib/hubspot/contact_spec.rb

Based on changes in adimichele/hubspot-ruby#58 pull request
Unfortunately it fails the test (see below) because it returns Contacts as JSON instead of Hubspot::Contact. Probably it will be better to keep 'vid-offset' parameter and at the same time initialize Contacts as they should be.
Hubspot::Contact.all all contacts must get the contacts list with paging data
Failure/Error: expect(first).to be_a Hubspot::Contact
expected {"addedAt"=>1405347851360, "vid"=>154835, "canonical-vid"=>154835, "merged-vids"=>[], "portal-id"=>62515, "is-contact"=>true, "profile-token"=>"AO_T-mNJu56Masvy-UGew0va-sSwlbSvfM2QxK1J7sd52Qci-gZCHybsgFoIwqgvmHq9f01ywtMLA6vB131sFPFEpkGAvl-bvEJ0ZB9xzpVbPkYVRmHfFIU3q9WfOStV1IMYOqGL9wYl", "profile-url"=>"https://app.hubspot.com/contacts/62515/lists/public/contact/_AO_T-mNJ …

Return Hubspot::Contact objects for paging calls

---

lib/hubspot/contact.rb

Sometimes a contact will have only name and phone number, with the current version there is no way to get it in the CRM because email is missing.
@adimichele please review.

Making email optional for contact creation

---

lib/hubspot/deal_pipeline.rb
lib/hubspot/properties.rb
spec/live/deal_pipeline_spec.rb

This pull requests adds the following functionality:
* Adds the ability to add a `single on/of checkbox` to a form using the api.
* Adds the ability to add a `currency` type to a company using the api.
* Adds the abililty to create a deal pipeline.

Add deal_pipeline creation, currency and single on/of checkbox

---

hubspot-ruby.gemspec

Some tests use rspec-its which is not part of rspec 3. Upgrading to rspec 3 is probably a good idea eventually, but this fixes the problem with running specs for now.

Pin rspec to 2.x

---

lib/hubspot/properties.rb

Hello Team,
This PR is to allow creating property with datatype as `date` through API request. This is in refernce  to issue - https://github.com/adimichele/hubspot-ruby/issues/69
Please review and suggest.
Thanks

Add date as valid property type in order to allow creating it through API request

---

spec/fixtures/vcr_cassettes/deal_find_by_company.yml
spec/lib/hubspot/deal_spec.rb

The `Hubspot::Deal.find_by_company` method was missing tests and fixtures. This was my first time using VCR and my Ruby chops are a wee bit rusty, so please don't be shy in your reviews.

Add spec and fixture for Deal.find_by_company method

---

lib/hubspot/engagement.rb

Attachments were not originally present in engagements output. I'm exposing them here since they're in the response hash.
See more here : https://developers.hubspot.com/docs/methods/engagements/engagements-overview

Retrieve attachments from engagement response if present

---

lib/hubspot/contact.rb

Contacts only return the properties portion of the hash from Hubspot.  It would be nice to be able to access the list-memberships so that it is easier to keep your application in sync with the lists a user belongs to in Hubspot.

Add list memberships to attribute accessors

---

lib/hubspot/contact.rb

Fixes issue https://github.com/adimichele/hubspot-ruby/issues/108
-----
When two contacts are merged in Hubspot, their emails are merged into a
comma-separated list. This list allows the contact to be found through
either email.
However, if the createOrUpdate endpoint matches on one of these
contacts and only one of the emails is passed in the properties hash,
Hubspot will attempt to update the email field. When using the email as
the identifier for a given Contact in createOrUpdate, the email should
not be included in the properties hash.

Prevents :email being passed in :properties for create_or_update!

---

lib/hubspot/engagement.rb

If you look at engagement update function, the params weren't actually being used to perform the update. Fixed to allow passed in params to update engagement.

Params in engagement update! wasn't being used and engagement was always

---

lib/hubspot-ruby.rb
lib/hubspot/config.rb
lib/hubspot/connection.rb
lib/hubspot/oauth.rb

- This commit lets the user pass an "access_token" to Hubspot.configure. At that point,
if an access token is passed, we set default headers on the Connection class, and this supports OAuth.
- I added a check in the get_url method which will not set an API key if an access token is present. This is required. Otherwise, Hubspot will fail the request, thinking that the api key was the intended auth method, but that the key was blank.
- I added an OAuth class to do simple creating/refreshing of the OAuth access tokens. For convenience here, I also added several of the params (like client id, and client secret) to the Hubspot.config method.
This has no tests yet. I've tested locally, but mainly looking to get your (@adimichele) thoughts to see if this direction seems acceptable, and if it's …

Added OAuth support.

---

lib/hubspot/engagement.rb

The Hubspot API allows an EngagementNote to be associated with a deal ID, but the option was missing from the EngagementNote.create!  method.  I added deal_id as an optional field to the method which should allow this gem to be backwards compatible.

add the ability to associate an engagement note with a deal id

---

lib/hubspot/engagement.rb
spec/fixtures/vcr_cassettes/engagement_associate.yml
spec/lib/hubspot/engagement_spec.rb

Allows to associate an existing engagement to an other object, as it is not possible via `update`

Add Engagement.associate!

---

lib/hubspot/form.rb
spec/lib/hubspot/form_spec.rb

Currently, if trying to initialise a Hubspot::Form then submit, you end up needing to also include `formFieldGroups` in the initialiser parameters. It would appear this should be optional for the purpose of Form initialisation when trying to submit.
The other alternative is to use the `find` class method but this seems somewhat unnecessary also (either the form exists and happy days, or it doesn't and an error will be raised when submitting).
This change allows the following use-case:
```
Hubspot::Form.new('guid' => 'my-form-guid').submit(my_form_hash)
```

Allow form to be initialised and submit without needing to call to `find`

---

lib/hubspot/company.rb
spec/live/companies_integration_spec.rb

Add new method `#all_with_offset` to return not only results as response but also `hasMore` and `offset`, so it would be possible to get all companies. For instance
```ruby
response = Hubspot::Company.all_with_offset(count: 100)
while response['hasMore']
response = Hubspot::Company.all_with_offset(count: 100, offset: response['offset'])
end
```

[feat/company-all-with-offset] improve Get all companies with other information

---

lib/hubspot-ruby.rb

There have been some requests to change the module name to use the stylized HubSpot name which is ultimately a large change for a small stylistic benefit. This change allows developers to use HubSpot or Hubspot without breaking backwards compatibility.

Add HubSpot module alias

---

README.md
spec/lib/hubspot/blog_spec.rb
spec/lib/hubspot/company_properties_spec.rb
spec/lib/hubspot/company_spec.rb
spec/lib/hubspot/contact_list_spec.rb
spec/lib/hubspot/contact_properties_spec.rb
spec/lib/hubspot/contact_spec.rb
spec/lib/hubspot/deal_properties_spec.rb
spec/lib/hubspot/form_spec.rb
spec/lib/hubspot/utils_spec.rb
spec/spec_helper.rb
spec/support/cassette_helper.rb
spec/support/vcr.rb

Note to the Reviewer:
This PR will fail on Travis until PR #138 is merged. The fact that Travis is now failing because VCR is now raising an error when encountering new requests is a sign that this change is working 😸 
Summary:
VCR defaults to using the record mode `:once`, which allows HTTP
interactions to be recorded when a cassette file doesn't exist but
raises when the cassette does exist and an unexpected request is made.
This behavior is currently being overridden in the `CassetteHelper` as
the record mode is being set to `:new_episodes`, which always allows new
HTTP interactions.
This PR:
- Sets the default record mode to `:none` to ensure new HTTP requests
are intentional.
- Exposes the env variable VCR_RECORD to facilitate recording new HTTP
interactions or updating existing …

Prevent VCR from making unexpected HTTP requests

---

.travis.yml
hubspot-ruby.gemspec

After updating the tests we now require at least Ruby 2.3, which is the oldest supported Ruby version.

Require at least Ruby 2.3

---

hubspot-ruby.gemspec

Summary:
This version bump includes a backwards compatibility fix to expose the
hubspot rake tasks to users and adds deprecation warnings.

bump version

---

hubspot-ruby.gemspec

Note to the Reviewer: This PR was reviewed and merged into v0-stable for the v0.6.1 gem release (PR #147 ). This is now being merged into master so the code lives in v0.6.1 and future versions.
Summary:
This version bump includes a backwards compatibility fix to expose the
hubspot rake tasks to users and adds deprecation warnings.

bump version to 0.6.1

---

hubspot-ruby.gemspec
spec/fixtures/vcr_cassettes/contact_list/add_contact_to_dynamic_list.yml
spec/fixtures/vcr_cassettes/contact_lists/add_contact.yml
spec/fixtures/vcr_cassettes/contact_lists/add_existing_contact.yml
spec/lib/hubspot-ruby_spec.rb
spec/lib/hubspot/connection_spec.rb
spec/lib/hubspot/contact_list_spec.rb
spec/spec_helper.rb

Summary:
In preparation for upgrading to RSpec 3, this PR removes the use of the
test double library, [rr], in favor of RSpec's mocking framework. One of
the owners of the rr library has stated they do not have plans to
support RSpec 3. See the issue [Support for Rspec 3] for more details.
While RSpec 2 does expose a 'mock' method, RSpec 3 removes 'mock'
and 'stub' in favor of 'double' to create test doubles. Visit
the [RSpec changelog] for more details.
[rr]: https://github.com/rr/rr
[Support for RSpec 3]: https://github.com/rr/rr/issues/65
[RSpec changelog]:
https://github.com/rspec/rspec-mocks/blob/master/Changelog.md#300beta1--2013-11-07

remove 'mock' in preparation of RSpec 3

---

hubspot-ruby.gemspec
spec/fixtures/vcr_cassettes/destroy_deal.yml
spec/lib/hubspot/company_properties_spec.rb
spec/lib/hubspot/company_spec.rb
spec/lib/hubspot/contact_list_spec.rb
spec/lib/hubspot/contact_properties_spec.rb
spec/lib/hubspot/contact_spec.rb
spec/lib/hubspot/deal_properties_spec.rb
spec/lib/hubspot/deal_spec.rb
spec/lib/hubspot/engagement_spec.rb
spec/lib/hubspot/form_spec.rb
spec/lib/hubspot/owner_spec.rb
spec/spec_helper.rb

Fixes #151 
Fixes #153 
Summary:
Upgrades RSpec to 3.8 and adds the [rspec-its] gem to maintain support
for the `its` style for writing tests.
This PR also:
- updates the deprecated `be_true` and `be_false` to use `be true`
and `be false`.
- updates/refactors tests that were flagged as pending
[rspec-its]: https://github.com/rspec/rspec-its

Upgrade RSpec

---

Gemfile

Summary:
Fetching a gem over http could allow a gem's source code to be
compromised in transit and the source code altered. To avoid any risk,
it's best to always use https.

Fetch gems over https

---

README.md

Address Issue: #18 
Summary:
Discovering the configuration options requires a bit of sleuthing. To
help our users, this lists the configuration options on the README in
addition to providing some helpful links to the HubSpot API Docs.

Update README to include configuration options

---

History.md
lib/hubspot/contact_properties.rb
spec/fixtures/vcr_cassettes/contact_properties/all_groups.yml
spec/fixtures/vcr_cassettes/contact_properties/all_properties.yml
spec/fixtures/vcr_cassettes/contact_properties/create_group.yml
spec/fixtures/vcr_cassettes/contact_properties/create_group_some_params.yml
spec/fixtures/vcr_cassettes/contact_properties/create_property.yml
spec/fixtures/vcr_cassettes/contact_properties/delete_group.yml
spec/fixtures/vcr_cassettes/contact_properties/delete_non_group.yml
spec/fixtures/vcr_cassettes/contact_properties/delete_non_property.yml
spec/fixtures/vcr_cassettes/contact_properties/delete_property.yml
spec/fixtures/vcr_cassettes/contact_properties/groups_included.yml
spec/fixtures/vcr_cassettes/contact_properties/groups_not_excluded.yml
spec/fixtures/vcr_cassettes/contact_properties/properties_in_groups.yml
spec/fixtures/vcr_cassettes/contact_properties/properties_not_in_groups.yml
spec/fixtures/vcr_cassettes/contact_properties/update_group.yml
spec/fixtures/vcr_cassettes/contact_properties/update_property.yml
spec/fixtures/vcr_cassettes/dump_contact_properties_and_groups.yml
spec/fixtures/vcr_cassettes/restore_contact_properties_and_groups.yml

Addresses Issue: #164 
Summary:
Updates the endpoints listed in `ContactProperties` to use the new
[HubSpot ContactProperty API endpoints].
The former endpoints still work because HubSpot implemented a redirect
that mapped the old endpoints to hit the new endpoints, resulting in a
response from the new endpoint.
[HubSpot ContactProperty API endpoints]:
https://developers.hubspot.com/docs/methods/contacts/contact-properties-overview

update contact property endpoints

---

History.md
lib/hubspot/company_properties.rb
spec/fixtures/vcr_cassettes/company_find_by_domain.yml
spec/fixtures/vcr_cassettes/company_properties/all_groups.yml
spec/fixtures/vcr_cassettes/company_properties/all_properties.yml
spec/fixtures/vcr_cassettes/company_properties/create_group.yml
spec/fixtures/vcr_cassettes/company_properties/create_group_some_params.yml
spec/fixtures/vcr_cassettes/company_properties/create_property.yml
spec/fixtures/vcr_cassettes/company_properties/delete_group.yml
spec/fixtures/vcr_cassettes/company_properties/delete_non_group.yml
spec/fixtures/vcr_cassettes/company_properties/delete_non_property.yml
spec/fixtures/vcr_cassettes/company_properties/delete_property.yml
spec/fixtures/vcr_cassettes/company_properties/exclude_by_group.yml
spec/fixtures/vcr_cassettes/company_properties/filter_by_group.yml
spec/fixtures/vcr_cassettes/company_properties/groups_excluded.yml
spec/fixtures/vcr_cassettes/company_properties/groups_included.yml
spec/fixtures/vcr_cassettes/company_properties/update_group.yml
spec/fixtures/vcr_cassettes/company_properties/update_property.yml
spec/lib/hubspot/company_properties_spec.rb

Addresses Issue #165 
Summary:
Updates the endpoints listed in `CompanyProperties` to use the new
[HubSpot CompanyProperty API] endpoints.
The former endpoints still work because HubSpot implemented a redirect
that mapped the old endpoints to hit the new endpoints, resulting in a
response from the new endpoint.
[HubSpot CompanyProperty API]:
https://developers.hubspot.com/docs/methods/companies/company-properties-overview

update company property endpoints

---

History.md
lib/hubspot/config.rb
lib/hubspot/utils.rb
spec/lib/hubspot/config_spec.rb

Summary:
Update `Hubspot.configure` to raise when the necessary authentication information is not provided or when two ways of authenticating are provided.

config cleanup with additional test coverage

---

hubspot-ruby.gemspec

Did you guys release a new version by mistake?
https://rubygems.org/gems/hubspot-ruby lists the version 0.7.0 now
If this was not by mistake, this will fix the version number in the `hubspot-ruby.gemspec` file.

bump version number to 0.7.0

---

hubspot-ruby.gemspec

Following the specifications here: https://guides.rubygems.org/specification-reference/#licenses=
This allows `hubspot-ruby` to play well with license checkers like https://github.com/newrelic/papers and also RubyGems to recognize licensing status.
Currently, it shows as N/A:

Add license to gemspec
